# This feature is in Beta.

# Please report any bugs to https://github.com/astronomer/astro-cli/issues

# NOTE: If putting a dict in conn_extra, please wrap in single quotes.

airflow:
  connections:
    - conn_id: vertica_mbo_test
      conn_type: Vertica
      conn_host: vertica-backup04.gsngames.com
      conn_login: dbadmin
      conn_password: mcdb
      conn_port: 5433
      conn_extra:
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value: